FROM eclipse-temurin:22-jre-noble

RUN apt-get update && apt-get install -y --no-install-recommends \
        # required tools
        graphviz \
        git \
        # optional tools
        python3 \
        ruby \
        nodejs \
        npm \
        golang-go \
        rustc \
        cargo \
        gcc \
        g++ \
        clang \
        make \
        gradle \
        maven \
        curl \
    && rm -rf /var/lib/apt/lists/*
